name: docker

on:
  push:
    branches:
      - master
  pull_request:
    types: [ synchronize, opened, reopened, labeled ]
    branches:
      - master

jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker images
        run: |
          export GOPATH=${GITHUB_WORKSPACE}/go
          export PATH=$PATH:$GOPATH/bin
          export IMAGE_TAG=latest
          make image-multiarch
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}